export const SURVEY_CREATE_REQUEST:String = "SURVEY_CREATE_REQUEST";
export const SURVEY_CREATE_SUCCESS:String = "SURVEY_CREATE_SUCCESS";
export const SURVEY_CREATE_FAIL:String = "SURVEY_CREATE_FAIL";
export const SURVEY_CREATE_RESET:String = "SURVEY_CREATE_RESET";


export const SURVEY_CREATE_REQUEST_PAGE2:String = "SURVEY_CREATE_REQUEST_PAGE2";
export const SURVEY_CREATE_SUCCESS_PAGE2:String = "SURVEY_CREATE_SUCCESS_PAGE2";
export const SURVEY_CREATE_FAIL_PAGE2:String = "SURVEY_CREATE_FAIL_PAGE2";
export const SURVEY_CREATE_RESET_PAGE2:String = "SURVEY_CREATE_RESET_PAGE2";
